baseURL = "https://origamando.com/"
languageCode = "it-it"
title = "Origamando"
theme = "blowfish"

[params]
  contentTypeName = "esperimenti"
  themeColor = "orange"
  showMenuItems = 3
  fullWidthTheme = false

  [params.author]
    name = "Professor Origami"
    email = "proforigami@origamando.com"

  [menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "esperimenti"
    name = "Esperimenti"
    url = "/esperimenti/"
    weight = 2

  [[menu.main]]
    identifier = "impatto"
    name = "Origamando Forest"
    url = "/impatto/"
    weight = 3