baseURL = "https://origamando.com/"
languageCode = "it-it"
title = "Origamando"
theme = "blowfish"

[params]
  contentTypeName = "esperimenti"
  themeColor = "orange"
  showMenuItems = 3
  fullWidthTheme = false

  [params.author]
    name = "Professor Origami"
    email = "nino@example.com"